### ISSUE TITLE
Suggestion: bundle git-clang-format

### ISSUE THREAD

**Issue by RedYetiDev** [lumirlumir/npm-clang-format-node#60]
It would be lovely if this library bundled `git-clang-format`, similar to Angular's `clang-format` library. This would be especially helpful for the use case of the clang formatter in Node.js (if this library is allowed to be used).

**Comment by lumirlumir** [comment]
@RedYetiDev Oh, I'll take a look at it and consider adding support for it. It might take a little time!

But I have one question: is there any difference between using `git-clang-format` and using `husky` with `lint-staged`?

Your answer to this question would be really helpful.

**Comment by RedYetiDev** [comment]
Yes. If I understand correctly, `lint-staged` will lint the entire staged file, whereas `git-clang-format` (available at <https://github.com/llvm/llvm-project/blob/main/clang/tools/clang-format/git-clang-format>) will make use of `clang-format`'s [`--lines`](https://github.com/llvm/llvm-project/blob/9043bdbce4ab1c6f07e72ddfedf7165bdf2b3e40/clang/tools/clang-format/git-clang-format#L515) argument

**Comment by lumirlumir** [comment]
Hello, @RedYetiDev,

At last, the prerelease version of `clang-format-node` is here!

I apologize for the delay. It took a bit more time than expected to add extra features beyond just `git-clang-format` and to write tests to ensure robustness.

Here’s a quick guide on how to use the new features (full documentation will be available before the official release).

---

## `git-clang-format`

You now have two options for using `git-clang-format`, so you can choose the one that best fits your setup. The usage is same to `angular/clang-format`.

### 1. Using with Python3 Dependency

This version has a smaller file size than `clang-format-git`, but it does require Python3 to run.

#### Installation

```bash
npm install -D clang-format-git-python
```

#### Usage

Run it with:

```
npx git-clang-format
```

or

```
npx clang-format-git-python
```

### 2. Using Without the Python3 Dependency

This package provides a standalone executable version of `git-clang-format`, so you won’t need to install Python3. But it's size is quite large. (about 40MB~50MB)

#### Installation

```bash
npm install -D clang-format-git
```

#### Usage

Run it with:

```
npx git-clang-format
```

or

```
npx clang-format-git-python
```

---

## APIs

If you’re looking to integrate `clang-format` tools, like `clang-format` or `git-clang-format`, directly into your workflow, you can now use the new APIs. These APIs return paths to the native binaries or scripts based on your OS and architecture.

### `clang-format` package

```javascript
const { clangFormatPath, getClangFormatPath } = require('clang-format-node');
```

### `clang-format-git` package

```javascript
const { gitClangFormatPath, getGitClangFormatPath } = require('clang-format-git');
```

### `clang-format-git-python` package

This package doesn’t include binaries. Instead, `gitClangFormatPath` returns the path to the `git-clang-format` Python script.

```javascript
const { gitClangFormatPath } = require('clang-format-git');
```

## Additional Notes

I’ve also added support for JSDoc type hints with these APIs, so you’ll see more detailed information directly in your code editor.

If you encounter any bugs or unexpected behavior, please let me know—I’ll be happy to take a look.
